info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    consul:
      path: /consul/**
      url: http://localhost:8083/consul
    provider:
      path: /provider/**
      url: http://localhost:8081/provider
  host:
    max-total-connections: 100
    max-per-route-connections: 10

eureka:
  client:
    enabled: false

server:
  port: 8080
